cities/urls.py
from django.urls import path
import cities.views as views

app_name = 'cities'

urlpatterns = [
    path('', views.home, name='home'),
    path('city/<int:pk>/', views.CityDetailView.as_view(), name='detail'),
    path('create/', views.CityCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete')
]

trains/urls.py
from django.urls import path
import trains.views as views

app_name = 'trains'

urlpatterns = [
    path('', views.home, name='home'),
    path('train/<int:pk>/', views.TrainDetailView.as_view(), name='detail'),
    path('create/', views.TrainCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.TrainDeleteView.as_view(), name='delete')
]

trains/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse

from cities.models import City  # Импорт моделей


class Train(models.Model):
    """ Модель поездов """
    name = models.CharField(max_length=50, unique=True, verbose_name='Название поезда')
    travel_time = models.PositiveSmallIntegerField(verbose_name='Время в пути')  # Время в пути
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='from_city_set',
                                  verbose_name='Откуда')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='to_city_set',
                                verbose_name='Куда')

    def __str__(self):
        return f'Поезд {self.name}'

    class Meta:
        verbose_name = 'Поезд'
        verbose_name_plural = 'Поезда'
        ordering = ['travel_time']

    def clean(self):
        if self.from_city == self.to_city:
            raise ValidationError('Город Прибытия = Городу Отправления')
        queryset = Train.objects.filter(
            from_city=self.from_city,
            to_city=self.to_city,
            travel_time=self.travel_time
        ).exclude(pk=self.pk)  # Исключит записи с определенными параметрами
        # Train == self.__class__
        if queryset.exists():
            raise ValidationError('Необходимо изменить время в пути')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('trains:detail', args=(self.id,))

trains/forms.py
from django import forms

from cities.models import City
from trains.models import Train


class TrainForm(forms.ModelForm):
    name = forms.CharField(label='Номер поезда', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите номер поезда'
    }))
    travel_time = forms.IntegerField(label='Время пути', widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите время пути'
    }))
    from_city = forms.ModelChoiceField(
        label='Откуда', queryset=City.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )
    to_city = forms.ModelChoiceField(
        label='Куда', queryset=City.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Train
        fields = '__all__'

trains/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator

from .models import Train
# from .forms import HtmlForm, TrainForm
from .forms import TrainForm


def home(request):
    if request.method == 'POST':
        form = TrainForm(request.POST)
        if form.is_valid():
            cf = form.cleaned_data
            Train.objects.create(
                name=cf['name']
            )

    form = TrainForm()
    trains = Train.objects.all()
    pages = Paginator(trains, 2)
    page_number = request.GET.get('page')
    page_obj = pages.get_page(page_number)
    context = {
        'trains': trains,
        'form': form,
        'page_obg': page_obj
    }
    return render(request, 'trains/home.html', context=context)


class TrainDetailView(DetailView):
    queryset = Train.objects.all()
    template_name = 'trains/detail.html'


class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Train
    form_class = TrainForm
    template_name = 'trains/create.html'
    success_url = reverse_lazy('trains:home')
    success_message = f'Поезд создан успешно!'


class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Train
    form_class = TrainForm
    template_name = 'trains/update.html'
    success_message = f'Поезд отредактирован успешно!'


class TrainDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Train
    template_name = 'trains/delete.html'
    success_url = reverse_lazy('trains:home')
    success_message = f'Поезд удалён успешно!'

trains/templates/trains/create.html
{% extends 'base.html' %}
{% block title %}Создание поезда{% endblock %}

{% block content %}
    <h1>Создание поездов</h1>

    {% include 'form.html' with button='Сохранить' %}
{% endblock %}

trains/templates/trains/delete.html
{% extends 'base.html' %}
{% block title %}Создание поездов{% endblock %}

{% block content %}
    <h1>Удаление поездов</h1>
    <p>Вы точно хотите удалить: {{ object }}?</p>
    {% include 'form.html' with button='Удалить' %}

{% endblock %}

trains/templates/trains/detail.html
{% extends 'base.html' %}
{% block title %}Поезд{% endblock %}

{% block content %}
    <h1>Поезд</h1>
    <div class="row">
        <div class="col-md">
            <p>Название поезда:
                <span class="fw-bold">{{ train.name }}</span>
            </p>
            <p>Откуда:
                <span class="fw-bold">{{ train.from_city }}</span>
            </p>
            <p>Куда:
                <span class="fw-bold">{{ train.to_city }}</span>
            </p>
            <p>Время в пути:
                <span class="fw-bold">{{ train.travel_time }} минут</span>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'trains:home' %}">
                <button type="button" class="btn btn-dark">Назад к списку поездов</button>
            </a>
        </div>
    </div>
{% endblock %}

trains/templates/trains/home.html
{% extends 'base.html' %}
{% block title %}Список поездов{% endblock %}

{% block content %}
    <h1>Список поездов</h1>
    <div class="row">
        <div class="col-md-8 mx-auto my-2">
            <table class="table table-striped">
                <tr>
                    <th>Номер</th>
                    <th>Откуда</th>
                    <th>Куда</th>
                    <th>Время в пути</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
                {% for train in page_obg %}
                    <tr>
                        <td>
                            <a href="{{ train.get_absolute_url }}">
                                <p>{{ train.name }}</p>
                            </a>
                        </td>
                        <td>
                            {{ train.from_city }}
                        </td>
                        <td>
                            {{ train.to_city }}
                        </td>
                        <td>
                            {{ train.travel_time }}
                        </td>
                        {% if user.is_authenticated %}
                        <td>
                            <a href="{% url 'trains:update' train.id %}">
                                <button type="submit" class="btn btn-primary">Редактировать</button>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'trains:delete' train.id %}">
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </a>
                        </td>
                            {% else %}
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                    {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if page_obg.has_previous %}
                    <a class="page-link" href="?page={{ page_obg.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% endif %}
            </li>
            {% for page in page_obg.paginator.page_range %}
                <li class="page-item {% if page == page_obg.number %} active {% endif %}"><a class="page-link"
                                                                                             href="?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}
            <li class="page-item">
                {% if page_obg.has_next %}
                    <a class="page-link " href="?page={{ page_obg.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
        </ul>
    </nav>

   {#     {% include 'form.html' with button='Отправить' action="/trains/create/" %}#}
{% endblock %}

trains/templates/trains/update.html
{% extends 'base.html' %}
{% block title %}Создание города{% endblock %}

{% block content %}
    <h1>Редактирование городов</h1>

    {% include 'form.html' with button='Обновить' %}

{% endblock %}