cities/urls.py
from django.urls import path
import cities.views as views

app_name = 'cities'

urlpatterns = [
    path('', views.home, name='home'),
    path('city/<int:pk>/', views.CityDetailView.as_view(), name='detail'),
    path('create/', views.CityCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete')
]

cities/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Имя города')

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cities:detail', args=(self.pk,))

cities/forms.py
from django import forms
from .models import City


class HtmlForm(forms.Form):
    name = forms.CharField(label='Город')


class CityForm(forms.ModelForm):
    name = forms.CharField(label='Город:',
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'Введите название города'}))

    class Meta:
        model = City
        fields = (
            'name',
        )

cities/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator

from .models import City
from .forms import HtmlForm, CityForm


def home(request):
    cities = City.objects.all()
    pages = Paginator(cities, 2)
    page_number = request.GET.get('page')
    page_obj = pages.get_page(page_number)
    context = {
        'page_obg': page_obj
    }
    return render(request, 'cities/home.html', context=context)


class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = 'cities/detail.html'


class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = City
    form_class = CityForm
    template_name = 'cities/create.html'
    success_url = reverse_lazy('cities:home')
    success_message = f'Город создан успешно!'


class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = City
    form_class = CityForm
    template_name = 'cities/update.html'
    # success_url = reverse_lazy('cities:detail')
    success_message = f'Город отредактирован успешно!'


class CityDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = City
    template_name = 'cities/delete.html'
    success_url = reverse_lazy('cities:home')
    success_message = f'Город удалён успешно!'

cities/templates/cities/create.html
{% extends 'base.html' %}
{% block title %}Создание города{% endblock %}

{% block content %}
    <h1>Создание городов</h1>

    {% include 'form.html' with button='Сохранить' %}
{% endblock %}

cities/templates/cities/delete.html
{% extends 'base.html' %}
{% block title %}Создание города{% endblock %}

{% block content %}
    <h1>Удаление городов</h1>
    <p>Вы точно хотите удалить: {{ object }}?</p>
    {% include 'form.html' with button='Удалить' %}

{% endblock %}

cities/templates/cities/detail.html
{% extends 'base.html' %}
{% block title %}Город{% endblock %}

{% block content %}
    <h1>Город</h1>
    <div class="row">
        <div class="col-md">
            <p>Название города:
                <span class="fw-bold">{{ city.name }}</span>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'cities:home' %}">
                <button type="button" class="btn btn-dark">Назад к списку</button>
            </a>
        </div>
    </div>
{% endblock %}

cities/templates/cities/home.html
{% extends 'base.html' %}
{% block title %}Список городов{% endblock %}

{% block content %}
    <h1>Список городов</h1>
    <div class="row">
        <div class="col-md-8 mx-auto my-2">
            <table class="table table-striped">
                {% for city in page_obg %}
                    <tr>
                        <td>
                            <a href="{{ city.get_absolute_url }}">
                                <p>{{ city.name }}</p>
                            </a>
                        </td>
                        {% if user.is_authenticated %}
                        <td>
                            <a href="{% url 'cities:update' city.id %}">
                                <button type="submit" class="btn btn-primary">Редактировать</button>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'cities:delete' city.id %}">
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </a>
                        </td>
                            {% else %}
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                    {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if page_obg.has_previous %}
                    <a class="page-link" href="?page={{ page_obg.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% endif %}
            </li>
            {% for page in page_obg.paginator.page_range %}
                <li class="page-item {% if page == page_obg.number %} active {% endif %}"><a class="page-link"
                                                                                             href="?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}
            <li class="page-item">
                {% if page_obg.has_next %}
                    <a class="page-link " href="?page={{ page_obg.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
        </ul>
    </nav>

{#     {% include 'form.html' with button='Отправить' action="/cities/create/" %}#}
{% endblock %}

cities/templates/cities/update.html
{% extends 'base.html' %}
{% block title %}Создание города{% endblock %}

{% block content %}
    <h1>Редактирование городов</h1>

    {% include 'form.html' with button='Обновить' %}

{% endblock %}