accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registration/', views.register_view, name='register')
]

cities/urls.py
from django.urls import path
import cities.views as views

app_name = 'cities'

urlpatterns = [
    path('', views.home, name='home'),
    path('city/<int:pk>/', views.CityDetailView.as_view(), name='detail'),
    path('create/', views.CityCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete')
]

trains/urls.py
from django.urls import path
import trains.views as views

app_name = 'trains'

urlpatterns = [
    path('', views.home, name='home'),
    path('train/<int:pk>/', views.TrainDetailView.as_view(), name='detail'),
    path('create/', views.TrainCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.TrainDeleteView.as_view(), name='delete')
]

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'list_routes' as list_routes_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:create' as train_create_url %}
{% url 'detail_routes' as route_detail  %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark container" style="background-color: mediumpurple;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Найди путь</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == cities_home_url %} active {% endif %}" aria-current="page"
                       href="{% url 'cities:home' %}">Города</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == trains_home_url %} active {% endif %}"
                       href="{% url 'trains:home' %}">Поезда</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == list_routes_url or request.path == route_detail %} active {% endif %}"
                       href="{% url 'list_routes' %}">Маршруты</a>
                </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path == cities_create_url or request.path == train_create_url%} active {% endif %}" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Добавить город/поезд
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'cities:create' %}">Добавить город</a></li>
                        <li><a class="dropdown-item" href="{% url 'trains:create' %}">Добавить поезд</a></li>
                    </ul>
                </li>
            {% else %}
            <li class="nav-item disabled">
                    <span class="nav-link">Добавить город/поезд</span>
                </li>
            {% endif %}
            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'accounts:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'accounts:register' %}">Регистрация</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'accounts:logout' %}">Выйти</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<div class="container">
    {% block content %}{% endblock content %}
</div>
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });
</script>
</body>
</html>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{ action }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{{ button }}</button>
        </form>
    </div>
</div>

templates/main.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<h1>Выберите пункт меню</h1>
{% endblock %}